### ISSUE TITLE
Wether there is a python version ?

### ISSUE THREAD

**Issue by HuangZuShu** [achang98/image-encryption-scheme-attacks#1]
Dear author,
I want to apply your code in other encryption method, but I have difficult in changing your code to python.
Would you mind helping me to realize it in python version ?
Thank you very much !

**Comment by ahchang98** [comment]
The reason this code was written in Matlab is because it is an attack on other previously written Matlab code for encryption. I don't see this code being rewritten in Python anytime soon, unfortunately. Let me know if I can be of any other help, though.

**Comment by ahchang98** [comment]
The reason this code was written in Matlab is because it is an attack on other previously written Matlab code for encryption. I don't see this code being rewritten in Python anytime soon, unfortunately. Let me know if I can be of any other help, though.
